### ISSUE TITLE
No feedback when Adding the same CSR twice through the frontend

### ISSUE THREAD

**Issue by gruyaume** [canonical/gocert#34]
#### Describe the bug

Using the frontend, when adding a CSR for the second time, we are getting no feedback that this CSR already exists. 

#### To Reproduce

1. Add a CSR
2. Add the same CSR

#### Expected behavior
Some feedback that the CSR can't be added

#### Potential Solution

Instead of showing "Valid CSR" with a green checkbox, we could display "This CSR was already recorded" and grey out the "Submit" button.

**Comment by kayra1** [comment]
This is definitely a bug with our error handling, but the proposed solution of greying out the submit button requires us to add the "check if csr is in list" logic in the frontend, which must run every time the textbox changes. This will be heavy on the client with the current set of existing browsers.

Instead, I've proposed adding an error notification in the form itself in the PR, which aligns with all of the other possible errors that occur for certificates and the forms that are in the users page.
